--- Dockerfile
+++ Dockerfile
@@ -103,13 +103,6 @@ ENV CUDA_TOOLKIT_PATH=/usr/local/cuda \
 # Build and install TF
 RUN ./nvbuild.sh --testlist --python$PYVER
 
-RUN git clone https://github.com/tensorflow/estimator -b r1.13 /opt/estimator && \
-    cd /opt/estimator && \
-    bazel build //tensorflow_estimator/tools/pip_package:build_pip_package && \
-    bazel-bin/tensorflow_estimator/tools/pip_package/build_pip_package /tmp/estimator_pip && \
-    pip install --no-cache-dir --upgrade /tmp/estimator_pip/*.whl && \
-    rm -rf ${HOME}/.cache/bazel /tmp/estimator_pip && bazel clean --expunge
-
 # Install DALI and build TF plugin, we need to have TF present already
 RUN DALI_VERSION=0.6.1 \
  && DALI_BUILD=608405 \
