#!/bin/bash

error=0
while read -r line || [[ -n "$line" ]]; do
    error=1
    name=`echo $line | awk -F "testlogs/" '{print $2}'`
    echo "<<< Reading test.log from $name >>>>"
    cat $line
    echo "<<< End of $name >>>"
done

exit $error
